//------------------------------------------------------------------------------
// <autogenerated>
//
//     Date: 11/18/2020 17:54
//
//     This code was generated by the ODDTool (Runtime Version: 1.9.0.0)
//     from file "DESU_OD.xml".
//     Supported HEP and ODD Primitives specification from 1.7 to 1.10.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </autogenerated>
//------------------------------------------------------------------------------

// include required interface
#include "OD_types.h"
#include "OD_ObjectInitStructs.h"

/*-------------------------------------------------------------------------------------------*/
/*---------  OBJECT DICTIONARY ID = DESU ----------------------------------------------------*/
/*-------------------------------------------------------------------------------------------*/

#ifndef ODD_RAM_ITEM
#define ODD_RAM_ITEM
#endif

#ifndef ODD_RAM_COLLECTION_ITEM
#define ODD_RAM_COLLECTION_ITEM ODD_RAM_ITEM
#endif

// INDEX 1000 - 

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1000[3];
const T_RomInit_eVersion3_8 pbROM_DESU_0x1000 = {(MBUInt8)OD_VERSION3_8, "BaseODVersion", 1, 10, 0};  //TYPE, NAME, X, Y, Z

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1001[3];
const T_RomInit_eVersion3_8 pbROM_DESU_0x1001 = {(MBUInt8)OD_VERSION3_8, "AppVersion", BUILD_APP_VERSION_MAJOR, BUILD_APP_VERSION_MINOR, BUILD_APP_VERSION_PATCH};  //TYPE, NAME, X, Y, Z

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1002_data[8*4];
ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1002[10];
const T_RomInit_eError pbROM_DESU_0x1002 = {(MBUInt8)OD_ERROR, "AppError", 0, //TYPE, NAME, CURRENT_ERROR
                                        {OD_RO_ACCESS, 8*4, MB_NULL, pbRAM_DESU_0x1002_data}, //bDataType, dwSizeInBytes, pbROMdata, pbRAMdata
                                        0, 8}; //OLDEST_ERROR_INDEX, MAX_HISTORY_SIZE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1003[4];
const T_RomInit_eState pbROM_DESU_0x1003 = {(MBUInt8)OD_STATE, "AppState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1004[8];
const T_RomInit_eCommand pbROM_DESU_0x1004 = {(MBUInt8)OD_COMMAND, "AppCommand", 0,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

const MBChar pbROM_DESU_0x1005_String[] = "DESU";
ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1005[sizeof(pbROM_DESU_0x1005_String)];
const T_RomInit_eString pbROM_DESU_0x1005 = {(MBUInt8)OD_STRING, "AppName", pbROM_DESU_0x1005_String};  //TYPE, NAME, STRING

//ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x1006[0];  // no memory RAM
const T_RomInit_eNullDevice pbROM_DESU_0x1006 = {(MBUInt8)OD_NULL_DEVICE, "End of index=1000"}; //TYPE, NAME

// INDEX 2000 - 

// DESU (detector supplies) block diagram

// 

// DESU power supply control

// DESU HV_GEN (High Voltage Generator) Control

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2000[4];
const T_RomInit_eState pbROM_DESU_0x2000 = {(MBUInt8)OD_STATE, "HvGenState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2001[8];
const T_RomInit_eCommand pbROM_DESU_0x2001 = {(MBUInt8)OD_COMMAND, "HvGenCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2002[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2002 = {(MBUInt8)OD_ADC_LIN, "AdcHvGen", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 25, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2003[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2003 = {(MBUInt8)OD_ADC_LIN, "Adc4kV", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, -5000, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2004[28];
const T_RomInit_eDAC_Lin pbROM_DESU_0x2004 = {(MBUInt8)OD_DAC_LIN, "Dac4kV", 0, //TYPE, NAME, DAC_RAW_INPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 4000, 0, 4095};  //UNIT, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

// DESU SUP_90V Control

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2005[4];
const T_RomInit_eState pbROM_DESU_0x2005 = {(MBUInt8)OD_STATE, "Sup90VState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2006[8];
const T_RomInit_eCommand pbROM_DESU_0x2006 = {(MBUInt8)OD_COMMAND, "Sup90VCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2007[4];
const T_RomInit_eState pbROM_DESU_0x2007 = {(MBUInt8)OD_STATE, "CblDet90V1", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2008[4];
const T_RomInit_eState pbROM_DESU_0x2008 = {(MBUInt8)OD_STATE, "CblDet90V2", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2009[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2009 = {(MBUInt8)OD_ADC_LIN, "Adc90V", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 125, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

// DESU SUP_LVDFE Control

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x200A[4];
const T_RomInit_eState pbROM_DESU_0x200A = {(MBUInt8)OD_STATE, "SupLvdfeState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x200B[8];
const T_RomInit_eCommand pbROM_DESU_0x200B = {(MBUInt8)OD_COMMAND, "SupLvdfeCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x200C[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x200C = {(MBUInt8)OD_ADC_LIN, "AdcFsupTest", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 15, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

// DESU SUP_800V/250V Control

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x200D[4];
const T_RomInit_eState pbROM_DESU_0x200D = {(MBUInt8)OD_STATE, "Sup800V250VState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x200E[8];
const T_RomInit_eCommand pbROM_DESU_0x200E = {(MBUInt8)OD_COMMAND, "Sup800V250VCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x200F[28];
const T_RomInit_eDAC_Lin pbROM_DESU_0x200F = {(MBUInt8)OD_DAC_LIN, "DACSup800VRegulate", 2048, //TYPE, NAME, DAC_RAW_INPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 800, 0, 4095};  //UNIT, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2010[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2010 = {(MBUInt8)OD_ADC_LIN, "Adc800V", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 1000, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

// DESU relay control

// DESU REL_10KV Control

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2011[4];
const T_RomInit_eState pbROM_DESU_0x2011 = {(MBUInt8)OD_STATE, "Rel10kVState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2012[8];
const T_RomInit_eCommand pbROM_DESU_0x2012 = {(MBUInt8)OD_COMMAND, "Rel10kVCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2013[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2013 = {(MBUInt8)OD_ADC_LIN, "Adc10kV", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 12500, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

// DESU REL_STAGE Control

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2014[4];
const T_RomInit_eState pbROM_DESU_0x2014 = {(MBUInt8)OD_STATE, "RelStageState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2015[8];
const T_RomInit_eCommand pbROM_DESU_0x2015 = {(MBUInt8)OD_COMMAND, "RelStageCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2016[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2016 = {(MBUInt8)OD_ADC_LIN, "AdcStageCurrentMeas", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICCURRENT, 16, 0.00000005, -0.0000002, 0, 65535};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2017[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2017 = {(MBUInt8)OD_ADC_LIN, "AdcStageCurrentMeasAverage", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICCURRENT, 16, 0.00000005, -0.0000002, 0, 65535};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2018[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x2018 = {(MBUInt8)OD_ADC_LIN, "AdcStageCurrentMeasMovingAverage", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICCURRENT, 16, 0.00000005, -0.0000002, 0, 65535};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2019[8];
const T_RomInit_eFloat64 pbROM_DESU_0x2019 = {(MBUInt8)OD_FLOAT64, "StageCurrentOffset", -0.00000040025};  //TYPE, NAME, PARAMETER

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x201A[8];
const T_RomInit_eFloat64 pbROM_DESU_0x201A = {(MBUInt8)OD_FLOAT64, "StageCurrentMultiplier", 0.12525};  //TYPE, NAME, PARAMETER

// touch alarm

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x201B[4];
const T_RomInit_eState pbROM_DESU_0x201B = {(MBUInt8)OD_STATE, "CblDetStage", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x201C[4];
const T_RomInit_eState pbROM_DESU_0x201C = {(MBUInt8)OD_STATE, "CblDetTaMotion", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x201D[4];
const T_RomInit_eState pbROM_DESU_0x201D = {(MBUInt8)OD_STATE, "TaActive", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x201E[4];
const T_RomInit_eState pbROM_DESU_0x201E = {(MBUInt8)OD_STATE, "TaDetected", 0}; //TYPE, NAME, STATE

// overvoltage/undervoltage protection

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x201F[4];
const T_RomInit_eState pbROM_DESU_0x201F = {(MBUInt8)OD_STATE, "ProtectionState", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2020[8];
const T_RomInit_eCommand pbROM_DESU_0x2020 = {(MBUInt8)OD_COMMAND, "ProtectionCommand", 0xFE1CFE1C,0};  //TYPE, NAME, COMMAND, PREVIOUS_COMMAND

//ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x2021[0];  // no memory RAM
const T_RomInit_eNullDevice pbROM_DESU_0x2021 = {(MBUInt8)OD_NULL_DEVICE, "End of index=2000"}; //TYPE, NAME

// INDEX 8000 - 

// TAD

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8000[4];
const T_RomInit_eState pbROM_DESU_0x8000 = {(MBUInt8)OD_STATE, "BoardRevision", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8001[3];
const T_RomInit_eVersion3_8 pbROM_DESU_0x8001 = {(MBUInt8)OD_VERSION3_8, "FirmwareVersion", 0, 0, 0};  //TYPE, NAME, X, Y, Z

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8002[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x8002 = {(MBUInt8)OD_ADC_LIN, "Adc5vrefTest", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 6.25, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8003[40];
const T_RomInit_eADC_Lin pbROM_DESU_0x8003 = {(MBUInt8)OD_ADC_LIN, "Adc24vTest", 0, //TYPE, NAME, ADC_RAW_OUTPUT
                                          (MBUInt8)OD_SI_ELECTRICPOTENTIAL, 12, 0, 25, 0, 4095};  //UNIT, RESOLUTION, DBL_MIN, DBL_MAX, UI_MIN, UI_MAX

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8004[4];
const T_RomInit_eState pbROM_DESU_0x8004 = {(MBUInt8)OD_STATE, "PowerOk", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8005[4];
const T_RomInit_eState pbROM_DESU_0x8005 = {(MBUInt8)OD_STATE, "HvInterlock", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8006[4];
const T_RomInit_eState pbROM_DESU_0x8006 = {(MBUInt8)OD_STATE, "LvInterlock", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8007[4];
const T_RomInit_eState pbROM_DESU_0x8007 = {(MBUInt8)OD_STATE, "TaDetectedRaw", 0}; //TYPE, NAME, STATE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8008[4];
const T_RomInit_eConfiguration pbROM_DESU_0x8008 = {(MBUInt8)OD_CONFIGURATION, "NfueFirst", 0};  //TYPE, NAME, PARAMETER

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8009_data[8*4];
ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8009[10];
const T_RomInit_eError pbROM_DESU_0x8009 = {(MBUInt8)OD_ERROR, "NfueLast", 0, //TYPE, NAME, CURRENT_ERROR
                                        {OD_RO_ACCESS, 8*4, MB_NULL, pbRAM_DESU_0x8009_data}, //bDataType, dwSizeInBytes, pbROMdata, pbRAMdata
                                        0, 8}; //OLDEST_ERROR_INDEX, MAX_HISTORY_SIZE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800A[4];
const T_RomInit_eConfiguration pbROM_DESU_0x800A = {(MBUInt8)OD_CONFIGURATION, "NfueCount", 0};  //TYPE, NAME, PARAMETER

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800B[4];
const T_RomInit_eConfiguration pbROM_DESU_0x800B = {(MBUInt8)OD_CONFIGURATION, "NfueOdFirst", 0};  //TYPE, NAME, PARAMETER

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800C_data[8*4];
ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800C[10];
const T_RomInit_eError pbROM_DESU_0x800C = {(MBUInt8)OD_ERROR, "NfueOdLast", 0, //TYPE, NAME, CURRENT_ERROR
                                        {OD_RO_ACCESS, 8*4, MB_NULL, pbRAM_DESU_0x800C_data}, //bDataType, dwSizeInBytes, pbROMdata, pbRAMdata
                                        0, 8}; //OLDEST_ERROR_INDEX, MAX_HISTORY_SIZE

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800D[4];
const T_RomInit_eConfiguration pbROM_DESU_0x800D = {(MBUInt8)OD_CONFIGURATION, "NfueOdCount", 0};  //TYPE, NAME, PARAMETER

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800E[4];
const T_RomInit_eConfiguration pbROM_DESU_0x800E = {(MBUInt8)OD_CONFIGURATION, "AliveCount", 0};  //TYPE, NAME, PARAMETER

ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800F_Data[12];
ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x800F[9];
const T_RomInit_eData pbROM_DESU_0x800F = {(MBUInt8)OD_DATA, "UniqueID", 0, 12, //TYPE, NAME, ACTUAL_SIZE, MAX_SIZE
                                       {OD_RO_ACCESS, 12, MB_NULL, pbRAM_DESU_0x800F_Data}, //bDataType, dwSizeInBytes, pbROMdata, pbRAMdata
                                       FALSE}; //DATA_CHANGED

const MBChar pbROM_DESU_0x8010_String[] = "EmptyErrorStringEmptyErrorString";
ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8010[sizeof(pbROM_DESU_0x8010_String)];
const T_RomInit_eString pbROM_DESU_0x8010 = {(MBUInt8)OD_STRING, "ErrorString", pbROM_DESU_0x8010_String};  //TYPE, NAME, STRING

//ODD_RAM_ITEM MBUInt8 pbRAM_DESU_0x8011[0];  // no memory RAM
const T_RomInit_eNullDevice pbROM_DESU_0x8011 = {(MBUInt8)OD_NULL_DEVICE, "End of index=8000"}; //TYPE, NAME

ODD_RAM_COLLECTION_ITEM OD_T_ObjectCollection  pCollectionTable_DESU[] =
{
    // INDEX 1000 - 
    {OID_DESU_BASEODVERSION                  ,  5,     pVersion38,   pbRAM_DESU_0x1000, (MBUInt8*)&pbROM_DESU_0x1000, 0, 0},
    {OID_DESU_APPVERSION                     ,  5,     pVersion38,   pbRAM_DESU_0x1001, (MBUInt8*)&pbROM_DESU_0x1001, 0, 0},
    {OID_DESU_APPERROR                       ,  6,         pError,   pbRAM_DESU_0x1002, (MBUInt8*)&pbROM_DESU_0x1002, 0, 0},
    {OID_DESU_APPSTATE                       ,  3,         pState,   pbRAM_DESU_0x1003, (MBUInt8*)&pbROM_DESU_0x1003, 0, 0},
    {OID_DESU_APPCOMMAND                     ,  4,       pCommand,   pbRAM_DESU_0x1004, (MBUInt8*)&pbROM_DESU_0x1004, 0, 0},
    {OID_DESU_APPNAME                        ,  3,        pString,   pbRAM_DESU_0x1005, (MBUInt8*)&pbROM_DESU_0x1005, 0, 0},
    {OID_DESU_END_OF_INDEX1000               ,  2,    pNullDevice,         MB_NULL, (MBUInt8*)&pbROM_DESU_0x1006, 0, 0},
    // INDEX 2000 - 
    // DESU (detector supplies) block diagram
    // 
    // DESU power supply control
    // DESU HV_GEN (High Voltage Generator) Control
    {OID_DESU_HVGENSTATE                     ,  3,         pState,   pbRAM_DESU_0x2000, (MBUInt8*)&pbROM_DESU_0x2000, 0, 0},
    {OID_DESU_HVGENCOMMAND                   ,  4,       pCommand,   pbRAM_DESU_0x2001, (MBUInt8*)&pbROM_DESU_0x2001, 0, 0},
    {OID_DESU_ADCHVGEN                       ,  9,       pADC_Lin,   pbRAM_DESU_0x2002, (MBUInt8*)&pbROM_DESU_0x2002, 0, 0},
    {OID_DESU_ADC4KV                         ,  9,       pADC_Lin,   pbRAM_DESU_0x2003, (MBUInt8*)&pbROM_DESU_0x2003, 0, 0},
    {OID_DESU_DAC4KV                         ,  9,       pDAC_Lin,   pbRAM_DESU_0x2004, (MBUInt8*)&pbROM_DESU_0x2004, 0, 0},
    // DESU SUP_90V Control
    {OID_DESU_SUP90VSTATE                    ,  3,         pState,   pbRAM_DESU_0x2005, (MBUInt8*)&pbROM_DESU_0x2005, 0, 0},
    {OID_DESU_SUP90VCOMMAND                  ,  4,       pCommand,   pbRAM_DESU_0x2006, (MBUInt8*)&pbROM_DESU_0x2006, 0, 0},
    {OID_DESU_CBLDET90V1                     ,  3,         pState,   pbRAM_DESU_0x2007, (MBUInt8*)&pbROM_DESU_0x2007, 0, 0},
    {OID_DESU_CBLDET90V2                     ,  3,         pState,   pbRAM_DESU_0x2008, (MBUInt8*)&pbROM_DESU_0x2008, 0, 0},
    {OID_DESU_ADC90V                         ,  9,       pADC_Lin,   pbRAM_DESU_0x2009, (MBUInt8*)&pbROM_DESU_0x2009, 0, 0},
    // DESU SUP_LVDFE Control
    {OID_DESU_SUPLVDFESTATE                  ,  3,         pState,   pbRAM_DESU_0x200A, (MBUInt8*)&pbROM_DESU_0x200A, 0, 0},
    {OID_DESU_SUPLVDFECOMMAND                ,  4,       pCommand,   pbRAM_DESU_0x200B, (MBUInt8*)&pbROM_DESU_0x200B, 0, 0},
    {OID_DESU_ADCFSUPTEST                    ,  9,       pADC_Lin,   pbRAM_DESU_0x200C, (MBUInt8*)&pbROM_DESU_0x200C, 0, 0},
    // DESU SUP_800V/250V Control
    {OID_DESU_SUP800V250VSTATE               ,  3,         pState,   pbRAM_DESU_0x200D, (MBUInt8*)&pbROM_DESU_0x200D, 0, 0},
    {OID_DESU_SUP800V250VCOMMAND             ,  4,       pCommand,   pbRAM_DESU_0x200E, (MBUInt8*)&pbROM_DESU_0x200E, 0, 0},
    {OID_DESU_DACSUP800VREGULATE             ,  9,       pDAC_Lin,   pbRAM_DESU_0x200F, (MBUInt8*)&pbROM_DESU_0x200F, 0, 0},
    {OID_DESU_ADC800V                        ,  9,       pADC_Lin,   pbRAM_DESU_0x2010, (MBUInt8*)&pbROM_DESU_0x2010, 0, 0},
    // DESU relay control
    // DESU REL_10KV Control
    {OID_DESU_REL10KVSTATE                   ,  3,         pState,   pbRAM_DESU_0x2011, (MBUInt8*)&pbROM_DESU_0x2011, 0, 0},
    {OID_DESU_REL10KVCOMMAND                 ,  4,       pCommand,   pbRAM_DESU_0x2012, (MBUInt8*)&pbROM_DESU_0x2012, 0, 0},
    {OID_DESU_ADC10KV                        ,  9,       pADC_Lin,   pbRAM_DESU_0x2013, (MBUInt8*)&pbROM_DESU_0x2013, 0, 0},
    // DESU REL_STAGE Control
    {OID_DESU_RELSTAGESTATE                  ,  3,         pState,   pbRAM_DESU_0x2014, (MBUInt8*)&pbROM_DESU_0x2014, 0, 0},
    {OID_DESU_RELSTAGECOMMAND                ,  4,       pCommand,   pbRAM_DESU_0x2015, (MBUInt8*)&pbROM_DESU_0x2015, 0, 0},
    {OID_DESU_ADCSTAGECURRENTMEAS            ,  9,       pADC_Lin,   pbRAM_DESU_0x2016, (MBUInt8*)&pbROM_DESU_0x2016, 0, 0},
    {OID_DESU_ADCSTAGECURRENTMEASAVERAGE     ,  9,       pADC_Lin,   pbRAM_DESU_0x2017, (MBUInt8*)&pbROM_DESU_0x2017, 0, 0},
    {OID_DESU_ADCSTAGECURRENTMEASMOVINGAVERAGE,  9,       pADC_Lin,   pbRAM_DESU_0x2018, (MBUInt8*)&pbROM_DESU_0x2018, 0, 0},
    {OID_DESU_STAGECURRENTOFFSET             ,  3,       pFloat64,   pbRAM_DESU_0x2019, (MBUInt8*)&pbROM_DESU_0x2019, 0, 0},
    {OID_DESU_STAGECURRENTMULTIPLIER         ,  3,       pFloat64,   pbRAM_DESU_0x201A, (MBUInt8*)&pbROM_DESU_0x201A, 0, 0},
    // touch alarm
    {OID_DESU_CBLDETSTAGE                    ,  3,         pState,   pbRAM_DESU_0x201B, (MBUInt8*)&pbROM_DESU_0x201B, 0, 0},
    {OID_DESU_CBLDETTAMOTION                 ,  3,         pState,   pbRAM_DESU_0x201C, (MBUInt8*)&pbROM_DESU_0x201C, 0, 0},
    {OID_DESU_TAACTIVE                       ,  3,         pState,   pbRAM_DESU_0x201D, (MBUInt8*)&pbROM_DESU_0x201D, 0, 0},
    {OID_DESU_TADETECTED                     ,  3,         pState,   pbRAM_DESU_0x201E, (MBUInt8*)&pbROM_DESU_0x201E, 0, 0},
    // overvoltage/undervoltage protection
    {OID_DESU_PROTECTIONSTATE                ,  3,         pState,   pbRAM_DESU_0x201F, (MBUInt8*)&pbROM_DESU_0x201F, 0, 0},
    {OID_DESU_PROTECTIONCOMMAND              ,  4,       pCommand,   pbRAM_DESU_0x2020, (MBUInt8*)&pbROM_DESU_0x2020, 0, 0},
    {OID_DESU_END_OF_INDEX2000               ,  2,    pNullDevice,         MB_NULL, (MBUInt8*)&pbROM_DESU_0x2021, 0, 0},
    // INDEX 8000 - 
    // TAD
    {OID_DESU_BOARDREVISION                  ,  3,         pState,   pbRAM_DESU_0x8000, (MBUInt8*)&pbROM_DESU_0x8000, 0, 0},
    {OID_DESU_FIRMWAREVERSION                ,  5,     pVersion38,   pbRAM_DESU_0x8001, (MBUInt8*)&pbROM_DESU_0x8001, 0, 0},
    {OID_DESU_ADC5VREFTEST                   ,  9,       pADC_Lin,   pbRAM_DESU_0x8002, (MBUInt8*)&pbROM_DESU_0x8002, 0, 0},
    {OID_DESU_ADC24VTEST                     ,  9,       pADC_Lin,   pbRAM_DESU_0x8003, (MBUInt8*)&pbROM_DESU_0x8003, 0, 0},
    {OID_DESU_POWEROK                        ,  3,         pState,   pbRAM_DESU_0x8004, (MBUInt8*)&pbROM_DESU_0x8004, 0, 0},
    {OID_DESU_HVINTERLOCK                    ,  3,         pState,   pbRAM_DESU_0x8005, (MBUInt8*)&pbROM_DESU_0x8005, 0, 0},
    {OID_DESU_LVINTERLOCK                    ,  3,         pState,   pbRAM_DESU_0x8006, (MBUInt8*)&pbROM_DESU_0x8006, 0, 0},
    {OID_DESU_TADETECTEDRAW                  ,  3,         pState,   pbRAM_DESU_0x8007, (MBUInt8*)&pbROM_DESU_0x8007, 0, 0},
    {OID_DESU_NFUEFIRST                      ,  3, pConfiguration,   pbRAM_DESU_0x8008, (MBUInt8*)&pbROM_DESU_0x8008, 0, 0},
    {OID_DESU_NFUELAST                       ,  6,         pError,   pbRAM_DESU_0x8009, (MBUInt8*)&pbROM_DESU_0x8009, 0, 0},
    {OID_DESU_NFUECOUNT                      ,  3, pConfiguration,   pbRAM_DESU_0x800A, (MBUInt8*)&pbROM_DESU_0x800A, 0, 0},
    {OID_DESU_NFUEODFIRST                    ,  3, pConfiguration,   pbRAM_DESU_0x800B, (MBUInt8*)&pbROM_DESU_0x800B, 0, 0},
    {OID_DESU_NFUEODLAST                     ,  6,         pError,   pbRAM_DESU_0x800C, (MBUInt8*)&pbROM_DESU_0x800C, 0, 0},
    {OID_DESU_NFUEODCOUNT                    ,  3, pConfiguration,   pbRAM_DESU_0x800D, (MBUInt8*)&pbROM_DESU_0x800D, 0, 0},
    {OID_DESU_ALIVECOUNT                     ,  3, pConfiguration,   pbRAM_DESU_0x800E, (MBUInt8*)&pbROM_DESU_0x800E, 0, 0},
    {OID_DESU_UNIQUEID                       ,  6,          pData,   pbRAM_DESU_0x800F, (MBUInt8*)&pbROM_DESU_0x800F, 0, 0},
    {OID_DESU_ERRORSTRING                    ,  3,        pString,   pbRAM_DESU_0x8010, (MBUInt8*)&pbROM_DESU_0x8010, 0, 0},
    {OID_DESU_END_OF_INDEX8000               ,  2,    pNullDevice,         MB_NULL, (MBUInt8*)&pbROM_DESU_0x8011, 0, 0},
};

#define OD_NR_OF_COLLECTIONS_DESU 59

