//------------------------------------------------------------------------------
// <autogenerated>
//
//     Date: 11/18/2020 17:54
//
//     This code was generated by the ODDTool (Runtime Version: 1.9.0.0)
//     from file "DESU_OD.xml".
//     Supported HEP and ODD Primitives specification from 1.7 to 1.10.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </autogenerated>
//------------------------------------------------------------------------------

// INDEX 1000 - 
#define OID_GA_BASEODVERSION                        0x1000
#define OID_GA_APPVERSION                           0x1001
#define OID_GA_APPERROR                             0x1002
#define OID_GA_APPSTATE                             0x1003
#define OID_GA_APPCOMMAND                           0x1004
#define OID_GA_APPNAME                              0x1005
#define OID_GA_END_OF_INDEX1000                     0x1006
// INDEX 2000 - 
#define OID_GA_FIRMWAREVERSION                      0x2000
#define OID_GA_FWBUILDNR                            0x2001
#define OID_GA_FWLOGICALNAME                        0x2002
#define OID_GA_HWIDS                                0x2003
#define OID_GA_DESU                                 0x2004
#define OID_GA_INSTANCEID                           0x2005
#define OID_GA_END_OF_INDEX2000                     0x2006
// INDEX 8000 - 
#define OID_GA_END_OF_INDEX8000                     0x8000
