//------------------------------------------------------------------------------
// <autogenerated>
//
//     Date: 11/18/2020 17:54
//
//     This code was generated by the ODDTool (Runtime Version: 1.9.0.0)
//     from file "DESU_OD.xml".
//     Supported HEP and ODD Primitives specification from 1.7 to 1.10.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </autogenerated>
//------------------------------------------------------------------------------

// include headers with OID macros
#include "DESU_OD_GA_OID_Names.h"
#include "DESU_OD_DESU_OID_Names.h"

// include headers of OD tables
#include "DESU_OD_GA.h"
#include "DESU_OD_DESU.h"
